#Makefile for bubble sort with SCoPE and Skyeye

.PHONY: all scope clean distclean

all: scope 
	$(MAKE) -C ./scope
	clear

clean:
	$(MAKE) -C ./scope clean

distclean:
	$(MAKE) -C ./scope distclean

