#Makefile for bubble sort with SCoPE and Skyeye

.PHONY: all scope clean distclean

all: scope 

scope:
	$(MAKE) -C ./scope
	./scope/cjpeg

clean:
	$(MAKE) -C ./scope clean

distclean:
	$(MAKE) -C ./scope distclean

