all:
	make -C hello_world
	make -C hello_world_parameters
	make -C vocoder_gsm_NoC
	make -C vocoder/Coder_Posix_processes
	make -C variable_example
	make -C H264

clean:
	make -C hello_world clean
	make -C hello_world_parameters clean
	make -C vocoder_gsm_NoC clean
	make -C vocoder/Coder_Posix_processes clean
	make -C variable_example clean
	make -C H264 clean

distclean:
	make -C hello_world distclean
	make -C hello_world_parameters distclean
	make -C vocoder_gsm_NoC distclean
	make -C vocoder/Coder_Posix_processes distclean
	make -C variable_example distclean
	make -C H264 distclean

run:
	make -C hello_world run
	make -C hello_world_parameters run
	make -C vocoder_gsm_NoC run
	make -C vocoder/Coder_Posix_processes run
	make -C variable_example run
	make -C H264 run
